'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.ComponentModel.DataAnnotations

Partial Public Class Customers

    <Required>
    Public Property CustomerID As String

    <Required>
    <DisplayName("客戶名稱")>
    Public Property CompanyName As String

    <Required>
    <DisplayName("聯絡人")>
    Public Property ContactName As String

    <Required>
    <DisplayName("聯絡人職稱")>
    Public Property ContactTitle As String

    <DisplayName("客戶地址")>
    Public Property Address As String

    <DisplayName("城市")>
    Public Property City As String

    <DisplayName("地區")>
    Public Property Region As String

    <DisplayName("郵遞區號")>
    Public Property PostalCode As String

    <DisplayName("城市")>
    Public Property Country As String

    <Required>
    <DisplayName("連絡電話")>
    Public Property Phone As String

    <DisplayName("傳真")>
    Public Property Fax As String

    Public Overridable Property Orders As ICollection(Of Orders) = New HashSet(Of Orders)
    Public Overridable Property CustomerDemographics As ICollection(Of CustomerDemographics) = New HashSet(Of CustomerDemographics)

End Class
