'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbnorthwndEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbnorthwndEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Categories)
    Public Overridable Property CustomerDemographics() As DbSet(Of CustomerDemographics)
    Public Overridable Property Customers() As DbSet(Of Customers)
    Public Overridable Property Employees() As DbSet(Of Employees)
    Public Overridable Property Order_Details() As DbSet(Of Order_Details)
    Public Overridable Property Orders() As DbSet(Of Orders)
    Public Overridable Property Products() As DbSet(Of Products)
    Public Overridable Property Region() As DbSet(Of Region)
    Public Overridable Property Shippers() As DbSet(Of Shippers)
    Public Overridable Property Suppliers() As DbSet(Of Suppliers)
    Public Overridable Property Territories() As DbSet(Of Territories)

End Class
