'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Orders
    Public Property OrderID As Integer
    Public Property CustomerID As String
    Public Property EmployeeID As Nullable(Of Integer)
    Public Property OrderDate As Nullable(Of Date)
    Public Property RequiredDate As Nullable(Of Date)
    Public Property ShippedDate As Nullable(Of Date)
    Public Property ShipVia As Nullable(Of Integer)
    Public Property Freight As Nullable(Of Decimal)
    Public Property ShipName As String
    Public Property ShipAddress As String
    Public Property ShipCity As String
    Public Property ShipRegion As String
    Public Property ShipPostalCode As String
    Public Property ShipCountry As String

    Public Overridable Property Customers As Customers
    Public Overridable Property Employees As Employees
    Public Overridable Property Order_Details As ICollection(Of Order_Details) = New HashSet(Of Order_Details)
    Public Overridable Property Shippers As Shippers

End Class
